### ISSUE TITLE
Grunt, tests, and structure

### ISSUE THREAD

**Issue by calvinf** [americanbible/biblesearch-api-js#1]
Would you be opposed to the addition of Grunt of Gulp to this repository?  I'm interested in adding a Gruntfile to automate some aspects of this package including minification and make it easy to add and integrate tests as well.

I also have some ideas about the structure of the main JS file and am curious if you'd be willing to do some re-organization so the library can work well as a node.js module, too.

**Comment by bryceallison** [comment]
We'd welcome any updates or additions! Feel free to fork and submit a pull request.

**Comment by bradobro** [comment]
Hey @calvinf thanks for your willingness to make this repo better! Internally, we tend to prefer Gulp or simple node scripts to Grunt when feasible, but would love to see whatever you come up with.

**Comment by calvinf** [comment]
Great, I'll see what I can do.  I only discovered this repo recently.  I've been working on a simple Ruby tool to help me pump data from the Bible API to MongoDB.  Long-term, the JS version may be easier for me to work with and contribute to.

My tool is called [Bible-API-Thing](https://github.com/calvinf/Bible-API-Thing).  Now that I know about the Ruby gem I'll probably replace a good amount of the code here with your gem.

**Comment by bradobro** [comment]
Thanks Calvin!
