### ISSUE TITLE
Question about API Key and security

### ISSUE THREAD

**Issue by d4hines** [americanbible/biblesearch-api-js#2]
Hello,
I'd like to use your API in a bible search tool I'm making in NodeJS. It's meant for consumption by everyday users, but it's distributed as an npm package. So while the package is running in NodeJS, it's a user client, and not a server. I therefore need to distribute an API key with the package, which means it's accessible to anyone. That hurts me in my developer bones, but is it actually an issue in this case? Are there any alternatives?

Thanks,
Daniel Hines

**Comment by mark-bradshaw** [comment]
I no longer work for ABS, and I don't believe anyone inside ABS is watching this repo any more.  I'd suggest emailing support@bibles.org and see if you get a response.

**Comment by d4hines** [comment]
Ok, thanks.
